$(window).load((function() { var e = $("body"),
        t = $("#solar-system"); let s = document.querySelectorAll("#data a"),
        a = document.querySelectorAll("dt"),
        l = document.querySelectorAll(".planet");

        document.getElementById("welcomeButton").addEventListener("click", function(){
            $("#welcome").fadeOut()}
        )
        // $("#welcome button").click)

    function n() { $("#universe").css("display", "none"), $("#hello").css("display", "none"), $("#data").css("display", "none") } let i = $(location).attr("hash").split("#").pop();

    function c() { let e = Object.keys(assets); for (let t = 0; t < l.length; t++) l[t].title = e[t + 1], l[t].style.backgroundImage = "url(assets/still/" + assets[e[t + 1]].picSteady + ")" }
    i ? (assets[i].bio ? (document.getElementById("textSrc").innerHTML = assets[i].bio, $("#player").css("display", "block"), $("#textSrc").css("display", "block"), $("iframe").css("display", "none"), $("#data").css("display", "none"), document.body.style.setProperty("--playerOn", "rgba(0,0,0,0.8")) : (document.querySelector("iframe").src = assets[i].link, $("#player").fadeIn(), $("#antiplayer").fadeIn()), n()) : ($("#blackhole img").delay(2e3).fadeIn(3e3), $("#comet img").delay(2e3).fadeIn(3e3)), document.getElementById("blackhole").addEventListener("click", (function() { window.open("./blackhole/", "_self") })), $("#toggle-data").click((function(t) { e.toggleClass("data-open data-close"), t.preventDefault() })); let r = Object.keys(assets); for (let e = 0; e < l.length; e++) l[e].title = r[e + 1], l[e].style.backgroundImage = "url(assets/still/" + assets[r[e + 1]].picSteady + ")", l[e].addEventListener("mouseover", (t => { for (let e = 0; e < l.length; e++) l[e].style.backgroundImage = "url(assets/still/" + assets[r[e + 1]].picSteady + ")";
        l[e].style.backgroundImage = "url(assets/gif/" + assets[r[e + 1]].pic + ")" })); let o = 0;

    function d() { document.body.style.setProperty("--playerOn", "rgba(0,0,0,0.3"), $("#universe").fadeIn(), $("iframe").css("display", "block"), $("#player").fadeOut(), $("#antiplayer").fadeOut(), document.querySelector("iframe").src = "", document.getElementById("textSrc").innerHTML = "", document.querySelector("iframe").src = "", window.history.replaceState({ id: "home" }, "", "/"), $("#textSrc").css("display", "none"), $("#hello").fadeIn(), $("#data").css("display", "block") }
    Object.keys(assets).forEach((e => { s[o].innerHTML = assets[e].title, s[o].title = e, a[o].innerHTML = assets[e].title, o++ })), document.querySelector("#sun dt").innerHTML = assets.Bio.title, document.getElementById("player") && document.getElementById("closePlayer").addEventListener("click", (function() { d() })), $("#data a").click((function(e) { var s = $(this).attr("class"),
            a = this.title; if ("active" == this.classList[1]) { assets[a].bio ? (document.getElementById("textSrc").innerHTML = assets[a].bio, $("iframe").css("display", "none"), $("#textSrc").css("display", "block")) : document.querySelector("iframe").src = assets[a].link, $("#player").fadeIn(), n(); let e = { id: a };
            window.history.replaceState(e, a, "#" + a), $(`#${s} .planet`).css("background-image", `url(assets/still/${assets[this.title].picSteady})`) } else t.removeClass().addClass(s), c(), $(this).parent().find("a").removeClass("active"), $(this).addClass("active"), $(`#${s} .planet`).css("background-image", `url(assets/gif/${assets[this.title].pic})`);
        e.preventDefault() })), $(".orbit").click((function(e) { var s = $(this).attr("id"); let a = this.querySelector(".planet").title; var l = a; if ("active" == document.getElementsByClassName(s)[0].classList[1]) { document.querySelector("iframe").src = assets[l].link, $("#player").fadeIn(); let e = { id: l };
            window.history.replaceState(e, l, "#" + l), n() } else c(), t.removeClass().addClass(s), $("#data a").removeClass("active"), document.getElementsByClassName(s)[0].classList.add("active"), $(`#${s} .planet`).css("background-image", `url(assets/gif/${assets[a].pic})`);
        e.preventDefault() })), $("#sun").click((function(e) { var s = $(this).attr("id"); var a = "Bio"; if ("active" == document.getElementsByClassName(s)[0].classList[1]) { assets.Bio.bio ? (document.getElementById("textSrc").innerHTML = assets.Bio.bio, c(), $("iframe").css("display", "none"), $("#textSrc").css("display", "block")) : document.querySelector("iframe").src = assets.Bio.link, $("#player").fadeIn(); let e = { id: a };
            window.history.replaceState(e, a, "#Bio"), n() } else c(), t.removeClass().addClass(s), $("#data a").removeClass("active"), document.getElementsByClassName(s)[0].classList.add("active"), $(`#${s} .planet`).css("background-image", `url(assets/gif/${assets.Bio.pic})`);
        e.preventDefault() })), e.removeClass("view-2D opening").addClass("view-3D").delay(1e3).queue((function() { $(this).removeClass("hide-UI").addClass("set-speed"), $(this).dequeue() })), document.getElementById("toggle-fullscreen").addEventListener("click", (e => { var t, s, a, l;
        t = window.document, s = t.documentElement, a = s.requestFullscreen || s.mozRequestFullScreen || s.webkitRequestFullScreen || s.msRequestFullscreen, l = t.exitFullscreen || t.mozCancelFullScreen || t.webkitExitFullscreen || t.msExitFullscreen, t.fullscreenElement || t.mozFullScreenElement || t.webkitFullscreenElement || t.msFullscreenElement ? l.call(t) : a.call(s) })), window.innerHeight > window.innerWidth && $("#animationResp").fadeIn(), window.addEventListener("resize", (function() { window.innerHeight > window.innerWidth ? $("#animationResp").fadeIn() : $("#animationResp").fadeOut() })), $("#wait").fadeOut(2e3) }));